version: '3.8'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /srv/dev-disk-by-uuid-xxx/files/Movies:/movies
      - /files2/sonarr/config:/config
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /srv/dev-disk-by-uuid-xxx/files/Movies:/movies
      - /files2/radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - TZ=America/Chicago
    volumes:
      - /files2/homarr/config:/config
    ports:
      - 7575:7575
    restart: unless-stopped