version: '3'
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - 4533:4533
    environment:
      - ND_SCANINTERVAL=1h
      - ND_LOGLEVEL=info
    volumes:
      - /files2/navidrome-data:/data
      - /srv/dev-disk-by-uuid-yyy/files3/Music:/music
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  navidrome-watcher:
    image: containrrr/watchtower
    container_name: navidrome-watcher
    restart: unless-stopped
    command: --cleanup --label-enable navidrome
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock