services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=http://0.0.0.0:11434
      - OLLAMA_DEBUG=false
    volumes:
      - /root/.ollama/models:/root/.ollama/models
    restart: always
    network_mode: "host"