version: '3.8'
services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    restart: unless-stopped
    ports:
      - "2342:2342"
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    environment:
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_ADMIN_PASSWORD: "9612"
    volumes:
      - photoprism_storage:/photoprism/storage
      - /files2/Cloud files:/photoprism/originals
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  photoprism-watchtower:
    image: containrrr/watchtower
    container_name: photoprism-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 86400

volumes:
  photoprism_storage: